### ISSUE TITLE
git-trav:3: command not found: __open

### ISSUE THREAD

**Issue by vonpupp** [denolfe/zsh-travis#1]
Hello,

I am trying to use zsh-travis with antigen and I am having the following error:

```
git-trav:3: command not found: __open
```

I am not sure if it might be related that I already used oh-my-zsh before I installed antigen. Perhaps I should try a clean install with antigen first and install oh-my-zsh on top of antigen.

**Comment by denolfe** [comment]
Fixed by d6b9b7c
